class element():
    url = "https://opensource-demo.orangehrmlive.com/"
    mhusername = "/html/body/div/div[1]/div/div[1]/div/div[2]/div[2]/form/div[1]/div/div[2]/input"
    mhpass = "/html/body/div/div[1]/div/div[1]/div/div[2]/div[2]/form/div[2]/div/div[2]/input"
    btnlogin = "/html/body/div/div[1]/div/div[1]/div/div[2]/div[2]/form/div[3]/button"
    navbarAdmin = "/html/body/div/div[1]/div[1]/aside/nav/div[2]/ul/li[1]/a"
    menuOrganization= "/html/body/div/div[1]/div[1]/header/div[2]/nav/ul/li[3]"
    location = "/html/body/div/div[1]/div[1]/header/div[2]/nav/ul/li[3]/ul/li[2]"
    btnAdd = "/html/body/div/div[1]/div[2]/div[2]/div/div[2]/div[1]/div/button"
    mhname = "/html/body/div/div[1]/div[2]/div[2]/div/div/form/div[1]/div/div/div/div[2]/input"
    mhcity = "/html/body/div/div[1]/div[2]/div[2]/div/div/form/div[2]/div/div[1]/div/div[2]/input"
    mhprovince = "/html/body/div/div[1]/div[2]/div[2]/div/div/form/div[2]/div/div[2]/div/div[2]/input"
    mhzipcode = "/html/body/div/div[1]/div[2]/div[2]/div/div/form/div[2]/div/div[3]/div/div[2]/input"
    mhcountry = "/html/body/div/div[1]/div[2]/div[2]/div/div/form/div[2]/div/div[4]/div/div[2]/div/div/div[1]"
    mhnotelp = "/html/body/div/div[1]/div[2]/div[2]/div/div/form/div[2]/div/div[5]/div/div[2]/input"
    mhfax = "/html/body/div/div[1]/div[2]/div[2]/div/div/form/div[2]/div/div[6]/div/div[2]/input"
    mhaddress = "/html/body/div/div[1]/div[2]/div[2]/div/div/form/div[2]/div/div[7]/div/div[2]/textarea"
    mhnote = "/html/body/div/div[1]/div[2]/div[2]/div/div/form/div[2]/div/div[8]/div/div[2]/textarea"
    webdriverWait = "WebDriverWait(driver, 20)"
    btnsave = "/html/body/div/div[1]/div[2]/div[2]/div/div/form/div[3]/button[2]"
    btnCancel = "/html/body/div/div[1]/div[2]/div[2]/div/div/form/div[3]/button[1]"
    deleteSelected = "/html/body/div/div[1]/div[2]/div[2]/div/div[2]/div[3]/div/div[2]/div[1]/div/div[7]/div/button[1]"
    popUpyes ="/html/body/div/div[3]/div/div/div/div[3]/button[2]"
    popUpNo="/html/body/div/div[3]/div/div/div/div[3]/button[1]"
    messageDelete ="/html/body/div/div[2]"
    editSelected ="/html/body/div/div[1]/div[2]/div[2]/div/div[2]/div[3]/div/div[2]/div[1]/div/div[7]/div/button[2]"
    titleEditValidasi = "/html/body/div/div[1]/div[2]/div[2]/div/div/h6"
    requiredField ="//span[@class='oxd-text oxd-text--span oxd-input-field-error-message oxd-input-group__message']"